"""
Trend Models Analysis - Daily ranking dataset builder
"""

import logging
from datetime import date, datetime, time, timedelta
from typing import Any, Dict, List, Optional

import pandas as pd

from src.analysis.trend_models.features.extractor import extract_features_from_changes
from src.analysis.trend_models.utils.constants import (
    RANKING_MAX_CENSORING_SECONDS,
    RANKING_MIN_QUERY_SIZE,
)

logger = logging.getLogger(__name__)


def _parse_datetime(value: Any) -> Optional[datetime]:
    """Gerrit 形式を含む日時を datetime に変換する。"""
    if isinstance(value, datetime):
        return value
    if value is None:
        return None

    try:
        text = str(value).replace('.000000000', '').replace(' ', 'T')
        return datetime.fromisoformat(text)
    except (ValueError, TypeError):
        return None


def _build_change_index(changes: List[Dict[str, Any]]) -> Dict[int, Dict[str, Any]]:
    """change_number -> change のインデックスを作る。"""
    index = {}
    for change in changes:
        number = change.get('change_number')
        if number is None:
            number = change.get('_number')
        if number is None:
            continue
        index[int(number)] = change
    return index


def _is_change_open_at(change: Dict[str, Any], analysis_time: datetime) -> bool:
    """指定時刻で open だったかを判定する。"""
    created = _parse_datetime(change.get('created'))
    if created is None:
        return False
    if created > analysis_time:
        return False

    status = change.get('status', '')
    if status == 'NEW':
        return True

    closed_time = None
    if status == 'MERGED':
        closed_time = _parse_datetime(change.get('submitted') or change.get('merged') or change.get('updated'))
    elif status == 'ABANDONED':
        closed_time = _parse_datetime(change.get('updated'))

    # closed_time が不明な場合は conservative に open 扱いにする。
    if closed_time is None:
        return True

    return closed_time > analysis_time


def _is_bot(author: Dict[str, Any], bot_names: List[str]) -> bool:
    username = str(author.get('username', '')).lower()
    email = str(author.get('email', '')).lower()

    for bot_name in bot_names:
        token = bot_name.lower()
        if token and (token in username or token in email):
            return True

    return 'service_user' in [str(tag).lower() for tag in author.get('tags', [])]


def _get_first_non_bot_review_time(
    change: Dict[str, Any],
    after_time: datetime,
    bot_names: List[str],
) -> Optional[datetime]:
    """指定時刻以降の最初の非 bot レビュー時刻を返す。"""
    owner = change.get('owner', {})
    owner_email = str(owner.get('email', '')).lower()
    owner_username = str(owner.get('username', '')).lower()

    messages = change.get('messages', [])
    candidates = []

    for message in messages:
        msg_time = _parse_datetime(message.get('date'))
        if msg_time is None or msg_time < after_time:
            continue

        author = message.get('author', {})
        author_email = str(author.get('email', '')).lower()
        author_username = str(author.get('username', '')).lower()

        if _is_bot(author, bot_names):
            continue

        if author_email == owner_email and author_username == owner_username:
            continue

        if str(message.get('tag', '')).startswith('autogenerated:'):
            continue

        candidates.append(msg_time)

    if not candidates:
        return None

    return min(candidates)


def _to_day_start(dt: datetime) -> datetime:
    return datetime.combine(dt.date(), time.min)


def _iter_dates(start: datetime, end: datetime):
    """[start, end) を 1日刻みで返す。"""
    cursor = _to_day_start(start)
    end_day = _to_day_start(end)

    while cursor < end_day:
        yield cursor.date()
        cursor += timedelta(days=1)


def _build_query_id(
    project_name: str,
    release_version: str,
    period_type: str,
    analysis_date: date,
) -> str:
    return f"{project_name}_{release_version}_{period_type}_{analysis_date:%Y%m%d}"


def build_daily_ranking_dataset(
    project_name: str,
    release_version: str,
    period_type: str,
    period_start: datetime,
    period_end: datetime,
    all_changes: List[Dict[str, Any]],
    all_prs_df: pd.DataFrame,
    releases_df: pd.DataFrame,
    bot_names: List[str],
    min_query_size: int = RANKING_MIN_QUERY_SIZE,
    max_censoring_seconds: int = RANKING_MAX_CENSORING_SECONDS,
) -> pd.DataFrame:
    """日次 query ごとのランキング学習データを構築する。"""
    if period_start >= period_end:
        return pd.DataFrame()

    change_index = _build_change_index(all_changes)
    output_frames = []

    for analysis_date in _iter_dates(period_start, period_end):
        analysis_time = datetime.combine(analysis_date, time.min)

        open_changes = [
            change
            for change in all_changes
            if _is_change_open_at(change, analysis_time)
        ]

        if len(open_changes) < min_query_size:
            continue

        features_df = extract_features_from_changes(
            open_changes,
            all_prs_df,
            releases_df,
            project_name,
            analysis_time,
        )

        if features_df.empty:
            continue

        query_records = []
        for _, row in features_df.iterrows():
            change_number = row.get('change_number')
            if pd.isna(change_number):
                continue

            change_number = int(change_number)
            change = change_index.get(change_number)
            if change is None:
                continue

            row_analysis_time = row.get('analysis_time')
            if pd.isna(row_analysis_time):
                row_analysis_time = analysis_time
            elif hasattr(row_analysis_time, 'to_pydatetime'):
                row_analysis_time = row_analysis_time.to_pydatetime()

            first_review_time = _get_first_non_bot_review_time(change, row_analysis_time, bot_names)

            reviewed = 0
            time_to_review_seconds = float(max_censoring_seconds)

            if first_review_time is not None:
                delta = (first_review_time - row_analysis_time).total_seconds()
                if delta >= 0:
                    reviewed = 1
                    time_to_review_seconds = float(min(delta, max_censoring_seconds))

            record = row.to_dict()
            record.update({
                'project': project_name,
                'release': release_version,
                'period_type': period_type,
                'analysis_date': analysis_date,
                'query_id': _build_query_id(project_name, release_version, period_type, analysis_date),
                'first_review_time': first_review_time,
                'time_to_review_seconds': time_to_review_seconds,
                'reviewed': reviewed,
            })
            query_records.append(record)

        if len(query_records) < min_query_size:
            continue

        query_df = pd.DataFrame(query_records)
        query_df['review_priority_rank'] = (
            query_df['time_to_review_seconds']
            .rank(method='dense', ascending=True)
            .astype(float)
        )

        denom = max(len(query_df) - 1, 1)
        query_df['review_priority_rank_pct'] = (
            (query_df['review_priority_rank'] - 1.0) / float(denom)
        )
        query_df['query_size'] = len(query_df)

        output_frames.append(query_df)

    if not output_frames:
        return pd.DataFrame()

    result = pd.concat(output_frames, ignore_index=True)
    logger.info(
        "日次ランキングデータ生成: project=%s, release=%s, period=%s, rows=%d, queries=%d",
        project_name,
        release_version,
        period_type,
        len(result),
        result['query_id'].nunique(),
    )
    return result
