"""ボット/投稿者本人の判定と「次の人間レビュー」の抽出（§3.3）。

判定基準は background_problem.priority_distribution と同一。当面はここに置き、
将来 common へ昇格してもよい。
"""
from __future__ import annotations

import configparser
import csv
import logging
from datetime import datetime
from pathlib import Path

from src.analysis.background_problem.common.time_utils import parse_dt
from src.analysis.preliminary_analysis.concept_drift_existence.utils import constants

logger = logging.getLogger(__name__)


# ── ボット名の読み込み（3 一覧の和集合。すべて小文字で保持） ──────────
def _load_gerrymander_bots(config_path: Path) -> set[str]:
    bot_names: set[str] = set()
    config = configparser.ConfigParser()
    try:
        config.read(config_path)
        if "organization" in config and "bots" in config["organization"]:
            bot_names = {
                name.strip().lower()
                for name in config["organization"]["bots"].split(",")
                if name.strip()
            }
    except (configparser.Error, OSError) as e:
        logger.error(f"'{config_path}' の読み込みに失敗: {e}")
    return bot_names


def _load_bot_accounts_csv(csv_path: Path) -> set[str]:
    """third_party_ci_accounts.csv（name,email）から識別子集合を読む。"""
    ids: set[str] = set()
    if not Path(csv_path).exists():
        logger.warning(f"CI アカウント一覧 CSV が見つかりません: {csv_path}")
        return ids
    with open(csv_path, "r", encoding="utf-8") as f:
        for i, row in enumerate(csv.reader(f)):
            if not row:
                continue
            if i == 0 and [c.strip().lower() for c in row[:2]] == ["name", "email"]:
                continue
            for col in row[:2]:
                if col.strip():
                    ids.add(col.strip().lower())
    return ids


def _load_extra_bots(path: Path) -> set[str]:
    names: set[str] = set()
    if not Path(path).exists():
        logger.warning(f"追加ボット一覧が見つかりません: {path}")
        return names
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                names.add(line.lower())
    return names


def load_bot_names() -> set[str]:
    """ボット/自動アカウントの識別子集合（小文字、大文字小文字無視で照合）。"""
    names = _load_gerrymander_bots(constants.GERRYMANDER_CONFIG)
    names |= _load_bot_accounts_csv(constants.BOT_ACCOUNTS_CSV)
    names |= _load_extra_bots(constants.EXTRA_BOTS_FILE)
    logger.info(f"ボット/自動アカウント識別子数: {len(names)}")
    return names


# ── 人間判定・投稿者判定 ─────────────────────────────────
def _author_identifiers(author: dict) -> set[str]:
    if not isinstance(author, dict):
        return {str(author)} if author else set()
    ids = {str(author[k]) for k in ("name", "username", "email") if author.get(k)}
    if author.get("_account_id") is not None:
        ids.add(str(author["_account_id"]))
    return ids


def is_bot(author: dict, bot_names: set[str]) -> bool:
    """author がボットか（name/username/email/_account_id のいずれかが一致）。"""
    return bool({i.lower() for i in _author_identifiers(author)} & set(bot_names))


def is_owner(author: dict, change: dict) -> bool:
    """author が Change の投稿者本人か（_account_id → email → username/name の順）。"""
    owner = change.get("owner", {})
    if not isinstance(owner, dict) or not isinstance(author, dict):
        return False
    if owner.get("_account_id") is not None and author.get("_account_id") is not None:
        if owner["_account_id"] == author["_account_id"]:
            return True
    return any(owner.get(k) and author.get(k) and owner[k] == author[k]
               for k in ("email", "username", "name"))


def is_human_comment(message: dict, change: dict, bot_names: set[str]) -> bool:
    """メッセージが「人間のレビューコメント」か（自動生成/ボット/本人を除外）。"""
    tag = message.get("tag")
    if isinstance(tag, str) and tag.startswith("autogenerated:"):
        return False
    author = message.get("author", {})
    return not is_bot(author, bot_names) and not is_owner(author, change)


def human_comment_times(change: dict, bot_names: set[str]) -> list[datetime]:
    """Change の人間レビューコメント時刻の一覧（昇順）。"""
    times: list[datetime] = []
    for message in change.get("messages", []) or []:
        if isinstance(message, dict) and is_human_comment(message, change, bot_names):
            dt = parse_dt(message.get("date"))
            if dt is not None:
                times.append(dt)
    times.sort()
    return times


def next_human_review_after(change: dict, t: datetime, bot_names: set[str]) -> datetime | None:
    """計測時点 t より後の「次の人間レビューコメント」時刻。無ければ None。"""
    for dt in human_comment_times(change, bot_names):
        if dt > t:
            return dt
    return None
