"""ボット/投稿者本人の判定と「次の人間レビュー」の抽出（design.md §2）。

判定基準は background_problem.priority_distribution と同一。
（pretrained_encoders 自己完結のため本ディレクトリに持つ。concept_drift_detection には依存しない。）
"""
from __future__ import annotations

import configparser
import csv
import logging
import re
from datetime import datetime
from pathlib import Path

from src.analysis.background_problem.common.time_utils import parse_dt
from src.analysis.preliminary_analysis.pretrained_encoders.utils import constants

logger = logging.getLogger(__name__)


# ── ボット名の読み込み（3 一覧の和集合。すべて小文字で保持） ──────────
def _load_gerrymander_bots(config_path: Path) -> set[str]:
    bot_names: set[str] = set()
    config = configparser.ConfigParser()
    try:
        config.read(config_path)
        if "organization" in config and "bots" in config["organization"]:
            bot_names = {
                name.strip().lower()
                for name in config["organization"]["bots"].split(",")
                if name.strip()
            }
    except (configparser.Error, OSError) as e:
        logger.error(f"'{config_path}' の読み込みに失敗: {e}")
    return bot_names


def _load_bot_accounts_csv(csv_path: Path) -> set[str]:
    """third_party_ci_accounts.csv（name,email）から識別子集合を読む。"""
    ids: set[str] = set()
    if not Path(csv_path).exists():
        logger.warning(f"CI アカウント一覧 CSV が見つかりません: {csv_path}")
        return ids
    with open(csv_path, "r", encoding="utf-8") as f:
        for i, row in enumerate(csv.reader(f)):
            if not row:
                continue
            if i == 0 and [c.strip().lower() for c in row[:2]] == ["name", "email"]:
                continue
            for col in row[:2]:
                if col.strip():
                    ids.add(col.strip().lower())
    return ids


def _load_extra_bots(path: Path) -> set[str]:
    names: set[str] = set()
    if not Path(path).exists():
        logger.warning(f"追加ボット一覧が見つかりません: {path}")
        return names
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                names.add(line.lower())
    return names


def load_bot_names() -> set[str]:
    """ボット/自動アカウントの識別子集合（小文字、大文字小文字無視で照合）。"""
    names = _load_gerrymander_bots(constants.GERRYMANDER_CONFIG)
    names |= _load_bot_accounts_csv(constants.BOT_ACCOUNTS_CSV)
    names |= _load_extra_bots(constants.EXTRA_BOTS_FILE)
    logger.info(f"ボット/自動アカウント識別子数: {len(names)}")
    return names


# ── 人間判定・投稿者判定 ─────────────────────────────────
def _author_identifiers(author: dict) -> set[str]:
    if not isinstance(author, dict):
        return {str(author)} if author else set()
    ids = {str(author[k]) for k in ("name", "username", "email") if author.get(k)}
    if author.get("_account_id") is not None:
        ids.add(str(author["_account_id"]))
    return ids


def is_bot(author: dict, bot_names: set[str]) -> bool:
    """author がボットか（name/username/email/_account_id のいずれかが一致）。"""
    # bot_names が set なら複製しない（記録 1 件ごとに数千件の一覧を複製していて遅かった。判定は同じ）
    names = bot_names if isinstance(bot_names, (set, frozenset)) else set(bot_names)
    return bool({i.lower() for i in _author_identifiers(author)} & names)


def is_owner(author: dict, change: dict) -> bool:
    """author が Change の投稿者本人か（_account_id → email → username/name の順）。"""
    owner = change.get("owner", {})
    if not isinstance(owner, dict) or not isinstance(author, dict):
        return False
    if owner.get("_account_id") is not None and author.get("_account_id") is not None:
        if owner["_account_id"] == author["_account_id"]:
            return True
    return any(owner.get(k) and author.get(k) and owner[k] == author[k]
               for k in ("email", "username", "name"))


def is_human_comment(message: dict, change: dict, bot_names: set[str]) -> bool:
    """メッセージが「人間のレビューコメント」か（自動生成/ボット/本人を除外）。"""
    tag = message.get("tag")
    if isinstance(tag, str) and tag.startswith("autogenerated:"):
        return False
    author = message.get("author", {})
    return not is_bot(author, bot_names) and not is_owner(author, change)


def human_comment_times(change: dict, bot_names: set[str]) -> list[datetime]:
    """Change の人間レビューコメント時刻の一覧（昇順）。"""
    times: list[datetime] = []
    for message in change.get("messages", []) or []:
        if isinstance(message, dict) and is_human_comment(message, change, bot_names):
            dt = parse_dt(message.get("date"))
            if dt is not None:
                times.append(dt)
    times.sort()
    return times


def next_human_review_after(change: dict, t: datetime, bot_names: set[str]) -> datetime | None:
    """計測時点 t より後の「次の人間レビューコメント」時刻。無ければ None。"""
    for dt in human_comment_times(change, bot_names):
        if dt > t:
            return dt
    return None


# ── Open の期間（design.md §11.1） ───────────────────────────
# 放棄・復活の記録の 1 行目。6 件の収集データでは次の 2 つの書き方だけだった（2026-10 確認）。
#   "Abandoned" / "Patch Set 3: Abandoned"、"Restored" / "Patch Set 3: Restored"
_ABANDON_RE = re.compile(r"^(Patch Set \d+:\s*)?Abandoned")
_RESTORE_RE = re.compile(r"^(Patch Set \d+:\s*)?Restored")

# updated で代用した Change（取れなかった理由 -> change_number の集合）。実行の最後にログへ出す。
# open_periods は同じ Change について何度も呼ばれるので、件数ではなく Change の集合で持つ
fallback_changes: dict[str, set] = {}


def _note_fallback(reason: str, change: dict) -> None:
    fallback_changes.setdefault(reason, set()).add(change.get("change_number", change.get("_number")))


def _first_line(message: dict) -> str:
    return str(message.get("message", "")).split("\n", 1)[0].strip()


def merged_time(change: dict) -> datetime | None:
    """マージされた時刻（`submitted`）。MERGED 以外は None。

    `submitted` が無いときだけ `updated` で代用する（nova では 31,463 件中 2 件）。
    """
    if change.get("status") != "MERGED":
        return None
    dt = parse_dt(change.get("submitted"))
    if dt is None:
        _note_fallback("MERGED に submitted なし", change)
        dt = parse_dt(change.get("updated"))
    return dt


def open_periods(change: dict) -> list[tuple[datetime, datetime | None]]:
    """Change が Open だった期間の列 [(開いた時刻, 閉じた時刻 or None), ...]（時刻順）。

    作成で開き、放棄の記録で閉じ、復活の記録で開き、マージ（submitted）で閉じる。
    期間は [開いた時刻, 閉じた時刻) で、閉じた時刻が None なら最後まで Open（状態 NEW）。
    旧版は「作成 〜 updated」の 1 期間だった。updated はマージ後の通知や CI の結果で遅れ、
    放棄から復活までの閉じている間も Open とみなしていた。
    """
    created = parse_dt(change.get("created"))
    if created is None:
        return []

    events: list[tuple[datetime, str]] = []
    for m in change.get("messages", []) or []:
        if not isinstance(m, dict):
            continue
        line = _first_line(m)
        kind = "close" if _ABANDON_RE.match(line) else "open" if _RESTORE_RE.match(line) else None
        if kind is None:
            continue
        dt = parse_dt(m.get("date"))
        if dt is not None:
            events.append((dt, kind))
    events.sort(key=lambda e: e[0])

    status = change.get("status")
    if status == "MERGED":
        events.append((merged_time(change), "close"))
    elif status == "ABANDONED" and not any(k == "close" for _, k in events):
        # 放棄の記録が見つからない（6 件の収集データでは 0 件）
        _note_fallback("ABANDONED に放棄の記録なし", change)
        events.append((parse_dt(change.get("updated")) or created, "close"))

    periods: list[tuple[datetime, datetime | None]] = []
    start: datetime | None = created
    for dt, kind in events:
        if kind == "close" and start is not None:
            periods.append((start, max(dt, start)))
            start = None
        elif kind == "open" and start is None:
            start = dt
    if start is not None:
        if status in ("MERGED", "ABANDONED"):
            # 最後が復活で終わっているのに状態は閉じている（記録の矛盾）。updated で閉じる
            _note_fallback("閉じた Change が復活で終わっている", change)
            periods.append((start, max(parse_dt(change.get("updated")) or start, start)))
        else:
            periods.append((start, None))
    return periods


def is_open_at(periods: list[tuple[datetime, datetime | None]], t: datetime) -> bool:
    """t が Open の期間 [開いた時刻, 閉じた時刻) のどれかに入るか。"""
    return any(s <= t and (e is None or t < e) for s, e in periods)


def log_fallbacks() -> None:
    """updated で代用した件数をログに出す（design.md §11.1）。"""
    if fallback_changes:
        logger.warning("Open の期間で updated を代用: " + ", ".join(f"{k} {len(v)} 件" for k, v in fallback_changes.items()))
