"""
第 3・第 4 段階：ボット一覧の作成と指標の算出（design.md §5.3, §6.4）

収集済みデータだけを使うので追加の通信は要らない。

ボットの判定は src/utils/bot_detection.py（設計書 src/utils/bot_detection.md）を使う。
第 3 段階で活動量の多いアカウントを出すのは、判定の決まり（§1 の ①〜③）で拾えない
機械のアカウントを見つけるため。これを人間として数えると、CI の投稿がレビューとして集計されてしまう。
"""

from __future__ import annotations

import json
import logging
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, Iterator, List, Set

from src.collectors.project_selection.source_files import has_source
from src.config.path import DEFAULT_DATA_DIR
from src.utils.bot_detection import BotDetector

logger = logging.getLogger(__name__)

COLLECTED_DIR = DEFAULT_DATA_DIR / "openstack_collected"

# 自動投稿の判別は Gerrit の tag を主に使う。
# Gerrit は自動生成した message に autogenerated:* の tag を付ける（REST API の仕様）。
AUTOGENERATED_TAG_PREFIX = "autogenerated:"

# tag で取りこぼすものを補う正規表現。
# **公式の定義ではなく、本研究の調査で実際に返ってきた message から列挙したもの。**
# 例: Qt CI Bot は tag を付けずに投稿するため tag だけでは除けない（406 件が該当した）。
# 取りこぼしが見つかったらここに足す。
SUPPLEMENTARY_AUTOMATED_PATTERN = re.compile(
    r"^(Uploaded patch set"
    r"|Patch Set \d+:\s*(Code-Review|Verified|Sanity-Review|Commit-Queue|-?\d|\(\d+ comment)"
    r"|Change has been successfully"
    r"|Abandoned|Restored|Topic |Hashtag |Added to build|Staged for CI|Build |Removed )"
)


def is_automated_message(message: Dict[str, Any]) -> bool:
    """その message が自動投稿か。tag を主に使い、正規表現で補う。"""
    tag = message.get("tag") or ""
    if tag.startswith(AUTOGENERATED_TAG_PREFIX):
        return True
    return bool(SUPPLEMENTARY_AUTOMATED_PATTERN.match((message.get("message") or "").strip()))


def iter_changes(directory_name: str) -> Iterator[Dict[str, Any]]:
    """収集済みディレクトリの Change を 1 件ずつ読む。"""
    changes_dir = COLLECTED_DIR / directory_name / "changes"
    for path in changes_dir.glob("change_*.json"):
        try:
            with open(path, "r", encoding="utf-8") as f:
                yield json.load(f)
        except Exception:
            continue


def account_ranking(directory_name: str, detector: BotDetector,
                    limit: int = 50) -> List[Dict[str, Any]]:
    """アカウントごとの活動量を多い順に返す（第 3 段階の目視確認用）。

    ボットは活動量が突出するため、上位から公式資料と照合すれば
    一覧に載っていないものを見つけられる（design.md §5.3）。
    """
    created: Counter = Counter()
    posted: Counter = Counter()
    labels: Dict[str, Dict[str, Any]] = {}

    for change in iter_changes(directory_name):
        owner = change.get("owner") or {}
        key = (owner.get("email") or owner.get("name") or "").lower()
        if key:
            created[key] += 1
            labels.setdefault(key, owner)
        for message in change.get("messages") or []:
            author = message.get("author") or {}
            akey = (author.get("email") or author.get("name") or "").lower()
            if akey:
                posted[akey] += 1
                labels.setdefault(akey, author)

    rows = []
    for key in (created + posted).most_common(limit):
        identifier = key[0]
        account = labels.get(identifier, {})
        rows.append({
            "identifier": identifier,
            "name": account.get("name"),
            "created_changes": created.get(identifier, 0),
            "posted_messages": posted.get(identifier, 0),
            "judged_bot": detector.is_bot(account),
        })
    return rows


class RepositoryMetrics:
    """1 リポジトリ分の指標（design.md §6.4）。"""

    def __init__(self, repository: str):
        self.repository = repository
        self.changes = 0
        self.bot_changes = 0
        self.human_changes = 0
        self.human_comments = 0            # 人が作成した Change に付いた、人手の（自動でない）コメント
        self.revisions = 0
        self.reviewers: Counter = Counter()
        self.reviewed_changes = 0
        self.changes_with_source = 0       # E1：実装言語のファイルを含む Change

    def add(self, change: Dict[str, Any], detector: BotDetector) -> None:
        self.changes += 1
        if has_source(change):
            self.changes_with_source += 1
        if detector.is_bot(change.get("owner")):
            self.bot_changes += 1
            return

        self.human_changes += 1
        self.revisions += len(change.get("revisions") or {})

        seen: Set[str] = set()
        for message in change.get("messages") or []:
            author = message.get("author") or {}
            if detector.is_bot(author):
                continue
            if is_automated_message(message):
                continue
            self.human_comments += 1
            identifier = (author.get("email") or author.get("name") or "").lower()
            if identifier:
                seen.add(identifier)
        if seen:
            self.reviewed_changes += 1
            self.reviewers.update(seen)

    def as_row(self) -> Dict[str, Any]:
        human = self.human_changes or 1
        reviewed = self.reviewed_changes or 1
        top10 = {r for r, _ in self.reviewers.most_common(10)}
        return {
            "repository": self.repository,
            "changes": self.changes,
            "bot_ratio": self.bot_changes / (self.changes or 1),
            "human_comments_per_change": self.human_comments / human,
            "revisions_per_change": self.revisions / human,
            "reviewers": len(self.reviewers),
            "reviewed_ratio": self.reviewed_changes / human,
            "source_ratio": self.changes_with_source / (self.changes or 1),
            "top10_reviewer_share": sum(self.reviewers[r] for r in top10) / reviewed,
        }


def compute(directory_name: str, repository: str, detector: BotDetector,
            period_start: str, period_end: str) -> RepositoryMetrics:
    """収集済みデータから、対象期間に作成された Change の指標を出す。"""
    metrics = RepositoryMetrics(repository)
    for change in iter_changes(directory_name):
        created = (change.get("created") or "")[:10]
        if created and period_start <= created < period_end:
            metrics.add(change, detector)
    logger.info(f"{repository}: {metrics.changes:,} 件から指標を算出しました")
    return metrics
