"""ボットの判定（設計書：src/utils/bot_detection.md）。

アカウントは、次の ①〜④ のどれかに当てはまればボットとみなす（§1）。
  ① Gerrit の SERVICE_USER の印がある
  ② メールアドレスが gserviceaccount.com で終わる
  ③ name か display_name の最後の語が Bot・CI
  ④ 一覧ファイル（bot_accounts.csv）に載っている（ホスト必須。名前では照合しない）
"""
from __future__ import annotations

import csv
import logging
import re
from pathlib import Path
from urllib.parse import urlparse

from src.config.path import DEFAULT_CONFIG
from src.utils.constants import GERRIT_PROJECTS

logger = logging.getLogger(__name__)

BOT_ACCOUNTS_CSV = DEFAULT_CONFIG / "bot_accounts.csv"

# ③ 名前の最後の語（§1.3）
#   区切り（空白・_・-）のあとの ci / bot は大文字・小文字を区別しない
#   区切りがないときは、大文字の Bot / CI が小文字か数字の直後で終わるものだけ（Abbot・Talbot を拾わない）
SEP_PATTERN = re.compile(r"(?:^|[\s_\-])(ci|bot)$", re.IGNORECASE)
CAMEL_PATTERN = re.compile(r"[a-z0-9](Bot|CI)$")

SERVICE_USER_TAG = "SERVICE_USER"
GSERVICEACCOUNT_SUFFIX = "gserviceaccount.com"


def host_of(component: str) -> str:
    """GERRIT_PROJECTS[component]["host"] からホスト名を返す（スキームと /a を除く）。"""
    return urlparse(GERRIT_PROJECTS[component]["host"]).netloc


def name_says_bot(name: str | None) -> bool:
    """③ 名前の最後の語が Bot・CI か。"""
    if not name:
        return False
    name = str(name).strip()
    return bool(SEP_PATTERN.search(name) or CAMEL_PATTERN.search(name))


def _norm(value) -> str:
    return str(value).strip().lower() if value is not None else ""


def load_bot_accounts(host: str, accounts_csv: Path = BOT_ACCOUNTS_CSV) -> dict[str, set[str]]:
    """一覧ファイルから、host の行の account_id・username・email を読む（§2.2）。

    account_id は文字列のまま、username・email は小文字にして持つ。
    """
    ids: dict[str, set[str]] = {"account_id": set(), "username": set(), "email": set()}
    with open(accounts_csv, "r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            if (row.get("host") or "").strip() != host:
                continue
            account_id = (row.get("account_id") or "").strip()
            if account_id:
                ids["account_id"].add(account_id)
            for key in ("username", "email"):
                value = _norm(row.get(key))
                if value:
                    ids[key].add(value)
    return ids


class BotDetector:
    """1 つのホストのボット判定（§1）。一覧はホストで絞って読み込む。"""

    def __init__(self, host: str, accounts_csv: Path = BOT_ACCOUNTS_CSV):
        self.host = host
        self.listed = load_bot_accounts(host, accounts_csv)
        logger.info(f"ボット判定（{host}）：一覧の行の識別子 "
                    + ", ".join(f"{k} {len(v)}" for k, v in self.listed.items()))

    def reason(self, account: dict) -> str | None:
        """当てはまった決まり（"service_user" / "gserviceaccount" / "name" / "list"）。どれでもなければ None。"""
        if not isinstance(account, dict):
            return None
        if SERVICE_USER_TAG in (account.get("tags") or ()):
            return "service_user"
        if _norm(account.get("email")).endswith(GSERVICEACCOUNT_SUFFIX):
            return "gserviceaccount"
        if name_says_bot(account.get("name")) or name_says_bot(account.get("display_name")):
            return "name"
        account_id = account.get("_account_id")
        if account_id is not None and str(account_id) in self.listed["account_id"]:
            return "list"
        for key in ("username", "email"):
            value = _norm(account.get(key))
            if value and value in self.listed[key]:
                return "list"
        return None

    def is_bot(self, account: dict) -> bool:
        return self.reason(account) is not None


def is_owner(account: dict, change: dict) -> bool:
    """チケットの作成者本人か（_account_id → email → username/name の順）。"""
    owner = change.get("owner", {})
    if not isinstance(owner, dict) or not isinstance(account, dict):
        return False
    if owner.get("_account_id") is not None and account.get("_account_id") is not None:
        if owner["_account_id"] == account["_account_id"]:
            return True
    return any(owner.get(k) and account.get(k) and owner[k] == account[k]
               for k in ("email", "username", "name"))


def is_human_review_message(message: dict, change: dict, detector: BotDetector) -> bool:
    """§3 の決まりで、人間のレビューのメッセージか（autogenerated:・ボット・作成者本人を除く）。"""
    tag = message.get("tag")
    if isinstance(tag, str) and tag.startswith("autogenerated:"):
        return False
    author = message.get("author", {})
    return not detector.is_bot(author) and not is_owner(author, change)
