"""
スナップショット構築（design.md §5.2-5.4）。

ある計測時点 T について
  1. T 時点で open かつ未検証の母集合チケットを集める
  2. 各チケットの (verification_time - T) を算出（打ち切りあり）
  3. dense rank で順位を付与
する。
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, List, Optional

from src.analysis.shared_ranking.event_extractor import _parse_datetime

logger = logging.getLogger(__name__)


@dataclass
class _ChangeMeta:
    """change から事前計算した、スナップショット判定で使う基本情報。"""

    change_number: int
    created: datetime
    closed: Optional[datetime]
    status: str
    sorted_messages: List[Dict[str, Any]]


@dataclass
class PopulationItem:
    """スナップショット内の 1 母集合チケット。"""

    change_number: int
    change: Dict[str, Any]
    verification_time: Optional[datetime]
    time_to_review_seconds: float
    reviewed: int
    censored: int


def _is_bot(author: Dict[str, Any], bot_names: List[str]) -> bool:
    if not author:
        return False
    username = str(author.get("username", "")).lower()
    email = str(author.get("email", "")).lower()
    name = str(author.get("name", "")).lower()
    for token in bot_names:
        token_l = token.lower()
        if not token_l:
            continue
        if token_l in username or token_l in email or token_l in name:
            return True
    tags = author.get("tags", []) or []
    return "service_user" in [str(tag).lower() for tag in tags]


def _is_owner(author: Dict[str, Any], owner: Dict[str, Any]) -> bool:
    if not author or not owner:
        return False
    a_email = str(author.get("email", "")).lower()
    o_email = str(owner.get("email", "")).lower()
    if a_email and o_email and a_email == o_email:
        return True
    a_id = author.get("_account_id")
    o_id = owner.get("_account_id")
    if a_id is not None and o_id is not None and a_id == o_id:
        return True
    a_user = str(author.get("username", "")).lower()
    o_user = str(owner.get("username", "")).lower()
    if a_user and o_user and a_user == o_user:
        return True
    return False


def _build_change_meta(change: Dict[str, Any]) -> Optional[_ChangeMeta]:
    """messages を時刻昇順にソートし、close 時刻を求めた _ChangeMeta を作る。"""
    number = change.get("change_number")
    if number is None:
        number = change.get("_number")
    if number is None:
        return None
    try:
        change_number = int(number)
    except (TypeError, ValueError):
        return None

    created = _parse_datetime(change.get("created"))
    if created is None:
        return None

    status = str(change.get("status", "") or "")
    closed: Optional[datetime] = None
    if status == "MERGED":
        closed = (
            _parse_datetime(change.get("submitted"))
            or _parse_datetime(change.get("merged"))
            or _parse_datetime(change.get("updated"))
        )
    elif status == "ABANDONED":
        closed = _parse_datetime(change.get("updated"))
    # NEW は open

    raw_messages = change.get("messages", []) or []
    parsed_messages: List[Dict[str, Any]] = []
    for msg in raw_messages:
        if not isinstance(msg, dict):
            continue
        msg_dt = _parse_datetime(msg.get("date"))
        if msg_dt is None:
            continue
        parsed_messages.append({**msg, "_parsed_date": msg_dt})

    parsed_messages.sort(key=lambda m: m["_parsed_date"])

    return _ChangeMeta(
        change_number=change_number,
        created=created,
        closed=closed,
        status=status,
        sorted_messages=parsed_messages,
    )


def build_change_meta_index(
    all_changes: List[Dict[str, Any]],
) -> Dict[int, _ChangeMeta]:
    """change_number -> _ChangeMeta の辞書を作る。"""
    index: Dict[int, _ChangeMeta] = {}
    for change in all_changes:
        meta = _build_change_meta(change)
        if meta is None:
            continue
        index[meta.change_number] = meta
    logger.info("change meta index 構築: %d 件", len(index))
    return index


def _is_open_at(meta: _ChangeMeta, T: datetime) -> bool:
    if meta.created > T:
        return False
    if meta.status == "NEW":
        return True
    if meta.closed is None:
        # close 時刻不明 → 保守的に open 扱い
        return True
    return meta.closed > T


def _has_review_strictly_before(
    meta: _ChangeMeta,
    change: Dict[str, Any],
    T: datetime,
    bot_names: List[str],
) -> bool:
    """T より前に「非 bot かつ非 owner かつ非 autogenerated」のレビューが存在するか。"""
    owner = change.get("owner", {}) or {}
    for msg in meta.sorted_messages:
        msg_dt: datetime = msg["_parsed_date"]
        if msg_dt >= T:
            return False  # ソート済みなのでこれ以降も >= T
        author = msg.get("author", {}) or {}
        if _is_bot(author, bot_names):
            continue
        if _is_owner(author, owner):
            continue
        tag = str(msg.get("tag", "") or "")
        if tag.startswith("autogenerated:"):
            continue
        return True
    return False


def _first_non_bot_review_at_or_after(
    meta: _ChangeMeta,
    change: Dict[str, Any],
    T: datetime,
    bot_names: List[str],
) -> Optional[datetime]:
    """T 以降の最初の非 bot レビュー時刻を返す。"""
    owner = change.get("owner", {}) or {}
    for msg in meta.sorted_messages:
        msg_dt: datetime = msg["_parsed_date"]
        if msg_dt < T:
            continue
        author = msg.get("author", {}) or {}
        if _is_bot(author, bot_names):
            continue
        if _is_owner(author, owner):
            continue
        tag = str(msg.get("tag", "") or "")
        if tag.startswith("autogenerated:"):
            continue
        return msg_dt
    return None


def collect_population(
    measurement_time: datetime,
    change_meta_index: Dict[int, _ChangeMeta],
    change_dict_index: Dict[int, Dict[str, Any]],
    bot_names: List[str],
    max_censoring_seconds: int,
) -> List[PopulationItem]:
    """
    計測時点 T で「open かつ未検証」のチケット集合を返す。

    Args:
        measurement_time: T
        change_meta_index: change_number -> _ChangeMeta
        change_dict_index: change_number -> 元の change dict
        bot_names: bot 名一覧
        max_censoring_seconds: 打ち切り上限秒

    Returns:
        母集合 PopulationItem のリスト
    """
    population: List[PopulationItem] = []
    T = measurement_time

    for change_number, meta in change_meta_index.items():
        if not _is_open_at(meta, T):
            continue

        change = change_dict_index.get(change_number)
        if change is None:
            continue

        if _has_review_strictly_before(meta, change, T, bot_names):
            continue

        verification = _first_non_bot_review_at_or_after(meta, change, T, bot_names)

        if verification is None:
            time_to_review = float(max_censoring_seconds)
            reviewed = 0
            censored = 1
        else:
            delta = (verification - T).total_seconds()
            if delta < 0:
                delta = 0.0
            if delta > max_censoring_seconds:
                delta = float(max_censoring_seconds)
                reviewed = 0
                censored = 1
            else:
                delta = float(delta)
                reviewed = 1
                censored = 0
            time_to_review = delta

        population.append(
            PopulationItem(
                change_number=change_number,
                change=change,
                verification_time=verification,
                time_to_review_seconds=time_to_review,
                reviewed=reviewed,
                censored=censored,
            )
        )

    return population


def assign_dense_rank(values: List[float]) -> List[float]:
    """昇順 dense rank（同値は同順位、次は +1）を返す。1 始まり。"""
    if not values:
        return []
    sorted_unique = sorted(set(values))
    rank_map = {v: float(i + 1) for i, v in enumerate(sorted_unique)}
    return [rank_map[v] for v in values]
