"""
人間のレビューの時刻など、priority_distribution 固有の入力ヘルパー。

Change / リリース日の読み込み（`load_changes` / `load_release_dates` /
`get_release_cycle`）は共通モジュール `background_problem.common.data_loader` に集約し、
ここでは後方互換のために再エクスポートする。
ボット・作成者本人の判定は src/utils/bot_detection.py にまとめてある（設計書 src/utils/bot_detection.md）。
"""
from __future__ import annotations

import logging
from datetime import datetime

from src.analysis.background_problem.common.data_loader import (  # noqa: F401
    get_release_cycle,
    load_changes,
    load_release_dates,
)
from src.analysis.background_problem.common.time_utils import parse_dt
from src.utils.bot_detection import BotDetector, is_human_review_message

logger = logging.getLogger(__name__)


# ── 人間のレビューの時刻 ─────────────────────────────────
def human_comment_times(change: dict, detector: BotDetector) -> list[datetime]:
    """Change の人間レビューコメントの時刻一覧（昇順）を返す。

    人間のレビューかどうかは bot_detection.md §3 の決まり
    （autogenerated: の印・ボット・投稿者本人を除く）で判定する。
    """
    times: list[datetime] = []
    for message in change.get("messages", []) or []:
        if not isinstance(message, dict):
            continue
        if not is_human_review_message(message, change, detector):
            continue
        dt = parse_dt(message.get("date"))
        if dt is not None:
            times.append(dt)
    times.sort()
    return times
